"""added target status to ww samples

Revision ID: 00de69ad6eab
Revises: 8adc85dd9b92
Create Date: 2023-03-31 14:51:40.705301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '00de69ad6eab'
down_revision = '8adc85dd9b92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp__submissions')
    with op.batch_alter_table('_ww_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n1_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('n2_status', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_ww_samples', schema=None) as batch_op:
        batch_op.drop_column('n2_status')
        batch_op.drop_column('n1_status')

    # op.create_table('_alembic_tmp__submissions',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('rsl_plate_num', sa.VARCHAR(length=32), nullable=False),
    # sa.Column('submitter_plate_num', sa.VARCHAR(length=127), nullable=True),
    # sa.Column('submitted_date', sa.TIMESTAMP(), nullable=True),
    # sa.Column('submitting_lab_id', sa.INTEGER(), nullable=True),
    # sa.Column('sample_count', sa.INTEGER(), nullable=True),
    # sa.Column('extraction_kit_id', sa.INTEGER(), nullable=True),
    # sa.Column('submission_type', sa.VARCHAR(length=32), nullable=True),
    # sa.Column('technician', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('reagents_id', sa.VARCHAR(), nullable=True),
    # sa.Column('extraction_info', sqlite.JSON(), nullable=True),
    # sa.Column('run_cost', sa.FLOAT(), nullable=True),
    # sa.Column('uploaded_by', sa.VARCHAR(length=32), nullable=True),
    # sa.Column('pcr_info', sqlite.JSON(), nullable=True),
    # sa.ForeignKeyConstraint(['extraction_kit_id'], ['_kits.id'], ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['reagents_id'], ['_reagents.id'], ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['submitting_lab_id'], ['_organizations.id'], ondelete='SET NULL'),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('rsl_plate_num'),
    # sa.UniqueConstraint('submitter_plate_num')
    # )
    # ### end Alembic commands ###
