"""Change phone to tel in contact

Revision ID: 0160a72316f1
Revises: 3433de8908be
Create Date: 2025-12-11 10:21:16.573272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0160a72316f1'
down_revision = '3433de8908be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tel', sa.String(length=16), nullable=True))
        batch_op.drop_column('phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=16), nullable=True))
        batch_op.drop_column('tel')
    # ### end Alembic commands ###
