"""change abbreviation to _abbreviation

Revision ID: 0c78a30a5a75
Revises: 2cc5bd3d1f81
Create Date: 2026-01-21 07:53:19.858947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0c78a30a5a75'
down_revision = '2cc5bd3d1f81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id', 'equipment_id', 'equipmentrole_id'], ['procedure_id', 'equipment_id', 'equipmentrole_id'])

    with op.batch_alter_table('_submissiontype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_abbreviation', sa.String(length=4), nullable=True))
        batch_op.drop_column('abbreviation')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissiontype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbreviation', sa.VARCHAR(length=4), nullable=True))
        batch_op.drop_column('_abbreviation')

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
