"""empty message

Revision ID: 0ce451affd40
Revises: b7d3f9a1c2e4
Create Date: 2026-07-20 09:03:08.519954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0ce451affd40'
down_revision = 'b7d3f9a1c2e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_auditlog', schema=None) as batch_op:
        batch_op.drop_column('_misc_info')

    with op.batch_alter_table('_clientlab', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('_clientsubmissionsampleassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_clientsubmission', ['clientsubmission_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, '_sample', ['sample_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('_configitem', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.create_unique_constraint(None, ['key'])

    with op.batch_alter_table('_contact', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('_equipmentrole', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('_equipmentroleequipmentassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_equipment', ['equipment_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, '_equipmentrole', ['equipmentrole_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.alter_column('run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_PRO_basicrun_id', '_run', ['run_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.alter_column('_comment',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_procedure', ['procedure_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, '_equipmentrole', ['equipmentrole_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, '_equipment', ['equipment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('SEA_Process_id', '_processversion', ['processversion_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id', 'procedure_id', 'equipmentrole_id'], ['equipment_id', 'procedure_id', 'equipmentrole_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, '_tipslot', ['tipslot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('_procedurereagentlotassociation', schema=None) as batch_op:
        batch_op.alter_column('_comment',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_procedure', ['procedure_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, '_reagentrole', ['reagentrole_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, '_reagentlot', ['reagentlot_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('_proceduresampleassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_procedure', ['procedure_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, '_sample', ['sample_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('_proceduretype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_proceduretypeequipmentroleassociation', schema=None) as batch_op:
        batch_op.alter_column('_always_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('_proceduretypereagentroleassociation', schema=None) as batch_op:
        batch_op.alter_column('_always_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('_process', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_reagent', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_reagentlot', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_reagentrole', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_reagentrolereagentassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_reagent', ['reagent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, '_reagentrole', ['reagentrole_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('_results', schema=None) as batch_op:
        batch_op.alter_column('_is_sample',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('_resultstype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_info_key_order', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('_sample_key_order', sa.JSON(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('_run', schema=None) as batch_op:
        batch_op.alter_column('clientsubmission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_BS_clientsub_id', '_clientsubmission', ['clientsubmission_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('_runsampleassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_sample', ['sample_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, '_run', ['run_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('_submissiontype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('_tipslot', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_tipslot', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_submissiontype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('_runsampleassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_sample', ['sample_id'], ['id'])
        batch_op.create_foreign_key(None, '_run', ['run_id'], ['id'])

    with op.batch_alter_table('_run', schema=None) as batch_op:
        batch_op.drop_constraint('fk_BS_clientsub_id', type_='foreignkey')
        batch_op.create_foreign_key(None, '_clientsubmission', ['clientsubmission_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('clientsubmission_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('_resultstype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('_sample_key_order')
        batch_op.drop_column('_info_key_order')

    with op.batch_alter_table('_results', schema=None) as batch_op:
        batch_op.alter_column('_is_sample',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('_reagentrolereagentassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_reagent', ['reagent_id'], ['id'])
        batch_op.create_foreign_key(None, '_reagentrole', ['reagentrole_id'], ['id'])

    with op.batch_alter_table('_reagentrole', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_reagentlot', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_reagent', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_process', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_proceduretypereagentroleassociation', schema=None) as batch_op:
        batch_op.alter_column('_always_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('_proceduretypeequipmentroleassociation', schema=None) as batch_op:
        batch_op.alter_column('_always_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('_proceduretype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_proceduresampleassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_procedure', ['procedure_id'], ['id'])
        batch_op.create_foreign_key(None, '_sample', ['sample_id'], ['id'])

    with op.batch_alter_table('_procedurereagentlotassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_procedure', ['procedure_id'], ['id'])
        batch_op.create_foreign_key(None, '_reagentrole', ['reagentrole_id'], ['id'])
        batch_op.create_foreign_key(None, '_reagentlot', ['reagentlot_id'], ['id'])
        batch_op.alter_column('_comment',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)

    with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_tipslot', ['tipslot_id'], ['id'])
        batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id', 'equipment_id', 'equipmentrole_id'], ['procedure_id', 'equipment_id', 'equipmentrole_id'])

    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.drop_constraint('SEA_Process_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_equipment', ['equipment_id'], ['id'])
        batch_op.create_foreign_key(None, '_processversion', ['processversion_id'], ['id'])
        batch_op.create_foreign_key(None, '_equipmentrole', ['equipmentrole_id'], ['id'])
        batch_op.create_foreign_key(None, '_procedure', ['procedure_id'], ['id'])
        batch_op.alter_column('_comment',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)

    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.drop_constraint('fk_PRO_basicrun_id', type_='foreignkey')
        batch_op.create_foreign_key(None, '_run', ['run_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('run_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('_equipmentroleequipmentassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_equipment', ['equipment_id'], ['id'])
        batch_op.create_foreign_key(None, '_equipmentrole', ['equipmentrole_id'], ['id'])

    with op.batch_alter_table('_equipmentrole', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_contact', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_configitem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('key',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('_clientsubmissionsampleassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, '_sample', ['sample_id'], ['id'])
        batch_op.create_foreign_key(None, '_clientsubmission', ['clientsubmission_id'], ['id'])

    with op.batch_alter_table('_clientlab', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_auditlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_misc_info', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
