"""ProcessVersion.version to FLOAT

Revision ID: 0d8b7cfa36f6
Revises: fb71f3fd1bda
Create Date: 2025-08-11 10:15:44.589913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0d8b7cfa36f6'
down_revision = 'fb71f3fd1bda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_processversion', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               type_=sa.FLOAT(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_processversion', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.FLOAT(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
