"""Added control differential to Sample

Revision ID: 0dacd39e55f5
Revises: 3823847d1123
Create Date: 2025-10-09 12:33:39.357639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0dacd39e55f5'
down_revision = '3823847d1123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('_controltype')
    op.drop_table('_control')
    with op.batch_alter_table('_sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_control', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_sample', schema=None) as batch_op:
        batch_op.drop_column('is_control')

    # ### end Alembic commands ###
