"""added pcr info to wastewater subs

Revision ID: 0ee7ffa026b2
Revises: 3d80e4a17a26
Create Date: 2023-03-22 14:51:37.871062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee7ffa026b2'
down_revision = '3d80e4a17a26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcr_info', sa.JSON(), nullable=True))
        
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.drop_column('pcr_info')

    # ### end Alembic commands ###
