"""Adding in processes

Revision ID: 10c47a04559d
Revises: 94289d4e63e6
Create Date: 2024-01-05 13:25:02.468436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c47a04559d'
down_revision = '94289d4e63e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_process',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_equipmentroles_processes',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('equipmentroles_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipmentroles_id'], ['_equipment_roles.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], )
    )
    op.create_table('_submissiontypes_processes',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('equipmentroles_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipmentroles_id'], ['_submission_types.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_submissiontypes_processes')
    op.drop_table('_equipmentroles_processes')
    op.drop_table('_process')
    # ### end Alembic commands ###
