"""updating costs

Revision ID: 178203610c3b
Revises: afbdd9e46207
Create Date: 2023-02-02 09:31:05.748477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178203610c3b'
down_revision = 'afbdd9e46207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_kits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mutable_cost', sa.FLOAT(precision=2), nullable=True))
        batch_op.add_column(sa.Column('constant_cost', sa.FLOAT(precision=2), nullable=True))

    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_cost', sa.FLOAT(precision=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.drop_column('run_cost')

    with op.batch_alter_table('_kits', schema=None) as batch_op:
        batch_op.drop_column('constant_cost')
        batch_op.drop_column('mutable_cost')

    # ### end Alembic commands ###
