"""initial rebuild

Revision ID: 1d136e5fa108
Revises: 
Create Date: 2025-12-01 14:21:09.414143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d136e5fa108'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_auditlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('object', sa.String(length=64), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_clientlab',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cost_centre', sa.String(length=32), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_configitem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_equipment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('_nickname', sa.String(length=64), nullable=True),
    sa.Column('asset_number', sa.String(length=16), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_equipmentrole',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_proceduretype',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('plate_columns', sa.INTEGER(), nullable=True),
    sa.Column('plate_rows', sa.INTEGER(), nullable=True),
    sa.Column('plate_cost', sa.FLOAT(precision=2), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_process',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_reagent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('_eol_ext', sa.Interval(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cost_per_ml', sa.FLOAT(precision=2), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_reagentrole',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_resultstype',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_sample',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('_is_control', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_table('_submissiontype',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('defaults', sa.JSON(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_tips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('capacity', sa.INTEGER(), nullable=True),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_clientlab_contact',
    sa.Column('clientlab_id', sa.INTEGER(), nullable=True),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['clientlab_id'], ['_clientlab.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['_contact.id'], )
    )
    op.create_table('_clientsubmission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('submitter_plate_id', sa.String(length=127), nullable=True),
    sa.Column('_submitted_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('clientlab_id', sa.INTEGER(), nullable=True),
    sa.Column('submission_category', sa.String(length=64), nullable=True),
    sa.Column('sample_count', sa.INTEGER(), nullable=True),
    sa.Column('full_batch_size', sa.INTEGER(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('submissiontype_name', sa.String(), nullable=True),
    sa.Column('cost_centre', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clientlab_id'], ['_clientlab.id'], name='fk_BS_sublab_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['_contact.id'], name='fk_BS_contact_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submissiontype_name'], ['_submissiontype.name'], name='fk_BS_subtype_name', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submitter_plate_id')
    )
    op.create_table('_discount',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=True),
    sa.Column('clientlab_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.FLOAT(precision=2), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clientlab_id'], ['_clientlab.id'], name='fk_DIS_org_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], name='fk_DIS_procedure_type_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_equipment_process',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], )
    )
    op.create_table('_equipmentroleequipmentassociation',
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], ),
    sa.PrimaryKeyConstraint('equipmentrole_id', 'equipment_id')
    )
    op.create_table('_proceduretype_resulttype',
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=True),
    sa.Column('resultstype_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.ForeignKeyConstraint(['resultstype_id'], ['_resultstype.id'], )
    )
    op.create_table('_proceduretypeequipmentroleassociation',
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=False),
    sa.Column('static', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], ),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.PrimaryKeyConstraint('equipmentrole_id', 'proceduretype_id')
    )
    op.create_table('_proceduretypereagentroleassociation',
    sa.Column('reagentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=False),
    sa.Column('last_used', sa.String(length=32), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.ForeignKeyConstraint(['reagentrole_id'], ['_reagentrole.id'], ),
    sa.PrimaryKeyConstraint('reagentrole_id', 'proceduretype_id')
    )
    op.create_table('_process_tips',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('tips_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], ),
    sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], )
    )
    op.create_table('_processversion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.FLOAT(precision=2), nullable=True),
    sa.Column('_date_verified', sa.TIMESTAMP(), nullable=True),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.Column('_active', sa.INTEGER(), nullable=True),
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], name='fk_version_process_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_reagentlot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lot', sa.String(length=64), nullable=True),
    sa.Column('_expiry', sa.TIMESTAMP(), nullable=True),
    sa.Column('_active', sa.INTEGER(), nullable=True),
    sa.Column('reagent_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['reagent_id'], ['_reagent.id'], name='fk_REGLOT_reagent_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot')
    )
    op.create_table('_reagentrolereagentassociation',
    sa.Column('reagentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('reagent_id', sa.INTEGER(), nullable=False),
    sa.Column('ml_used_per_sample', sa.FLOAT(precision=3), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['reagent_id'], ['_reagent.id'], ),
    sa.ForeignKeyConstraint(['reagentrole_id'], ['_reagentrole.id'], ),
    sa.PrimaryKeyConstraint('reagentrole_id', 'reagent_id')
    )
    op.create_table('_submissiontype_proceduretype',
    sa.Column('submissiontype_id', sa.INTEGER(), nullable=True),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.ForeignKeyConstraint(['submissiontype_id'], ['_submissiontype.id'], )
    )
    op.create_table('_tipslot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tips_id', sa.INTEGER(), nullable=True),
    sa.Column('lot', sa.String(length=64), nullable=True),
    sa.Column('_expiry', sa.TIMESTAMP(), nullable=True),
    sa.Column('_active', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], name='fk_tips_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot')
    )
    op.create_table('_clientsubmissionsampleassociation',
    sa.Column('sample_id', sa.INTEGER(), nullable=False),
    sa.Column('clientsubmission_id', sa.INTEGER(), nullable=False),
    sa.Column('submission_rank', sa.INTEGER(), nullable=False),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clientsubmission_id'], ['_clientsubmission.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['_sample.id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'clientsubmission_id', 'submission_rank')
    )
    op.create_table('_run',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rsl_plate_number', sa.String(length=32), nullable=False),
    sa.Column('clientsubmission_id', sa.INTEGER(), nullable=True),
    sa.Column('_started_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('run_cost', sa.FLOAT(precision=2), nullable=True),
    sa.Column('signed_by', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.JSON(), nullable=True),
    sa.Column('custom', sa.JSON(), nullable=True),
    sa.Column('_completed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clientsubmission_id'], ['_clientsubmission.id'], name='fk_BS_clientsub_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rsl_plate_number')
    )
    op.create_table('_procedure',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('repeat_of_id', sa.INTEGER(), nullable=True),
    sa.Column('_started_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('_completed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('technician', sa.String(length=64), nullable=True),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=True),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], name='fk_PRO_proceduretype_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repeat_of_id'], ['_procedure.id'], name='fk_repeat_id'),
    sa.ForeignKeyConstraint(['run_id'], ['_run.id'], name='fk_PRO_basicrun_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_runsampleassociation',
    sa.Column('sample_id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['_run.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['_sample.id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'run_id')
    )
    op.create_table('_procedureequipmentassociation',
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('processversion_id', sa.INTEGER(), nullable=True),
    sa.Column('_start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('_end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('tipslot_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], ),
    sa.ForeignKeyConstraint(['processversion_id'], ['_processversion.id'], name='SEA_Process_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipslot_id'], ['_tipslot.id'], name='SEA_Tipslot_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('equipment_id', 'procedure_id', 'equipmentrole_id')
    )
    op.create_table('_procedurereagentlotassociation',
    sa.Column('reagentlot_id', sa.INTEGER(), nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.Column('reagentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], ),
    sa.ForeignKeyConstraint(['reagentlot_id'], ['_reagentlot.id'], ),
    sa.ForeignKeyConstraint(['reagentrole_id'], ['_reagentrole.id'], ),
    sa.PrimaryKeyConstraint('reagentlot_id', 'procedure_id', 'reagentrole_id')
    )
    op.create_table('_proceduresampleassociation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.Column('sample_id', sa.INTEGER(), nullable=False),
    sa.Column('row', sa.INTEGER(), nullable=True),
    sa.Column('column', sa.INTEGER(), nullable=True),
    sa.Column('procedure_rank', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['_sample.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'sample_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('_date_analyzed', sa.TIMESTAMP(), nullable=True),
    sa.Column('procedure_id', sa.INTEGER(), nullable=True),
    sa.Column('assoc_id', sa.INTEGER(), nullable=True),
    sa.Column('_img', sa.String(length=128), nullable=True),
    sa.Column('resultstype_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assoc_id'], ['_proceduresampleassociation.id'], name='fk_RES_ASSOC_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], name='fk_RES_procedure_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resultstype_id'], ['_resultstype.id'], name='fk_RES_resultstype_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_results')
    op.drop_table('_proceduresampleassociation')
    op.drop_table('_procedurereagentlotassociation')
    op.drop_table('_procedureequipmentassociation')
    op.drop_table('_runsampleassociation')
    op.drop_table('_procedure')
    op.drop_table('_run')
    op.drop_table('_clientsubmissionsampleassociation')
    op.drop_table('_tipslot')
    op.drop_table('_submissiontype_proceduretype')
    op.drop_table('_reagentrolereagentassociation')
    op.drop_table('_reagentlot')
    op.drop_table('_processversion')
    op.drop_table('_process_tips')
    op.drop_table('_proceduretypereagentroleassociation')
    op.drop_table('_proceduretypeequipmentroleassociation')
    op.drop_table('_proceduretype_resulttype')
    op.drop_table('_equipmentroleequipmentassociation')
    op.drop_table('_equipment_process')
    op.drop_table('_discount')
    op.drop_table('_clientsubmission')
    op.drop_table('_clientlab_contact')
    op.drop_table('_tips')
    op.drop_table('_submissiontype')
    op.drop_table('_sample')
    op.drop_table('_resultstype')
    op.drop_table('_reagentrole')
    op.drop_table('_reagent')
    op.drop_table('_process')
    op.drop_table('_proceduretype')
    op.drop_table('_equipmentrole')
    op.drop_table('_equipment')
    op.drop_table('_contact')
    op.drop_table('_configitem')
    op.drop_table('_clientlab')
    op.drop_table('_auditlog')
    # ### end Alembic commands ###
