"""ProcessVersion relationships updates

Revision ID: 1dee33ed43e6
Revises: 0d8b7cfa36f6
Create Date: 2025-08-11 10:51:02.191052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1dee33ed43e6'
down_revision = '0d8b7cfa36f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processversion_id', sa.INTEGER(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('SEA_Process_id', '_processversion', ['processversion_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('process_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('SEA_Process_id', type_='foreignkey')
        batch_op.create_foreign_key(None, '_process', ['process_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('processversion_id')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
