"""SubmissionReagentAssociations added

Revision ID: 238c3c3e5863
Revises: 2684f065037c
Create Date: 2023-12-05 12:57:17.446606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238c3c3e5863'
down_revision = '2684f065037c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_reagents_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(length=1024), nullable=True))
        batch_op.alter_column('reagent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_reagents_submissions', schema=None) as batch_op:
        batch_op.alter_column('submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reagent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
