"""Tips update

Revision ID: 2578b0c4adf8
Revises: 1dee33ed43e6
Create Date: 2025-08-11 13:29:00.999832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2578b0c4adf8'
down_revision = '1dee33ed43e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ref', sa.String(length=64), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('lot')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('ref')
        batch_op.drop_column('capacity')
        batch_op.drop_column('manufacturer')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
