"""Adding role tag to SubmissionEquipmentAssociation

Revision ID: 30aab47d6f12
Revises: bc7a74476609
Create Date: 2023-12-27 09:00:26.262904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aab47d6f12'
down_revision = 'bc7a74476609'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp__equipment')
    with op.batch_alter_table('_equipment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_equipment_submissions', schema=None) as batch_op:
        batch_op.drop_column('role')

    # op.create_table('_alembic_tmp__equipment',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('nickname', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('asset_number', sa.VARCHAR(length=16), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
