"""Further Streamlining equipment

Revision ID: 318ec502824a
Revises: b99debc3ed31
Create Date: 2025-08-14 11:22:10.247710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '318ec502824a'
down_revision = 'b99debc3ed31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    op.drop_table('_proceduretypeequipmentroleassociation_equipment')
    with op.batch_alter_table('_tips', schema=None) as batch_op:
        batch_op.drop_column('tiprole_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiprole_id', sa.INTEGER(), nullable=True))

    op.create_table('_proceduretypeequipmentroleassociation_equipment',
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('proceduretypeequipmentroleassociation_proceduretypeid', sa.INTEGER(), nullable=True),
    sa.Column('proceduretypeequipmentroleassociation_equipmentroleid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['proceduretypeequipmentroleassociation_equipmentroleid'], ['_proceduretypeequipmentroleassociation.equipmentrole_id'], ),
    sa.ForeignKeyConstraint(['proceduretypeequipmentroleassociation_proceduretypeid'], ['_proceduretypeequipmentroleassociation.proceduretype_id'], )
    )
    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
