"""Update to ProcedureReagentAssociation

Revision ID: 3823847d1123
Revises: db76a5452c47
Create Date: 2025-10-08 10:45:26.220661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3823847d1123'
down_revision = 'db76a5452c47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_procedurereagentlotassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reagentrole_id', sa.INTEGER(), nullable=False, default=1))
        batch_op.create_foreign_key("fk_proreglotassoc_regrole", '_reagentrole', ['reagentrole_id'], ['id'])
        batch_op.drop_column('reagentrole')



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('_procedurereagentlotassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reagentrole', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint("fk_proreglotassoc_regrole", type_='foreignkey')
        batch_op.drop_column('reagentrole_id')

    op.create_table('_auditlog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    sa.Column('changes', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
