"""added in other ww techs

Revision ID: 3d9a88bd4ecd
Revises: f7f46e72f057
Create Date: 2023-08-30 11:03:41.575219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9a88bd4ecd'
down_revision = 'f7f46e72f057'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext_technician', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pcr_technician', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.drop_column('pcr_technician')
        batch_op.drop_column('ext_technician')

    # ### end Alembic commands ###
