"""added last_used to reagenttype

Revision ID: 4c6221f01324
Revises: 7aadd731ff63
Create Date: 2023-07-07 14:32:24.064042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6221f01324'
down_revision = '7aadd731ff63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_reagent_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_reagent_types', schema=None) as batch_op:
        batch_op.drop_column('last_used')

    # ### end Alembic commands ###
