"""Initial rebuild

Revision ID: 522441c4c3d6
Revises: 
Create Date: 2025-08-06 14:50:14.894493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522441c4c3d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_clientlab',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cost_centre', sa.String(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_configitem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_controltype',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_equipment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('asset_number', sa.String(length=16), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_equipmentrole',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_proceduretype',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('plate_columns', sa.INTEGER(), nullable=True),
    sa.Column('plate_rows', sa.INTEGER(), nullable=True),
    sa.Column('allowed_result_methods', sa.JSON(), nullable=True),
    sa.Column('plate_cost', sa.FLOAT(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_process',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_reagentrole',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_sampletype',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_submissiontype',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('defaults', sa.JSON(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_tiprole',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_clientlab_contact',
    sa.Column('clientlab_id', sa.INTEGER(), nullable=True),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['clientlab_id'], ['_clientlab.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['_contact.id'], )
    )
    op.create_table('_clientsubmission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('submitter_plate_id', sa.String(length=127), nullable=True),
    sa.Column('submitted_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('clientlab_id', sa.INTEGER(), nullable=True),
    sa.Column('submission_category', sa.String(length=64), nullable=True),
    sa.Column('sample_count', sa.INTEGER(), nullable=True),
    sa.Column('full_batch_size', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.JSON(), nullable=True),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('submissiontype_name', sa.String(), nullable=True),
    sa.Column('cost_centre', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clientlab_id'], ['_clientlab.id'], name='fk_BS_sublab_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['_contact.id'], name='fk_BS_contact_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submissiontype_name'], ['_submissiontype.name'], name='fk_BS_subtype_name', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submitter_plate_id')
    )
    op.create_table('_discount',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=True),
    sa.Column('clientlab_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.FLOAT(precision=2), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clientlab_id'], ['_clientlab.id'], name='fk_DIS_org_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], name='fk_DIS_procedure_type_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_equipment_process',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], )
    )
    op.create_table('_equipmentrole_equipment',
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], )
    )
    op.create_table('_equipmentrole_process',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], )
    )
    op.create_table('_proceduretype_process',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], )
    )
    op.create_table('_proceduretypeequipmentroleassociation',
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=False),
    sa.Column('uses', sa.JSON(), nullable=True),
    sa.Column('static', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], ),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.PrimaryKeyConstraint('equipmentrole_id', 'proceduretype_id')
    )
    op.create_table('_proceduretypereagentroleassociation',
    sa.Column('reagentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=False),
    sa.Column('uses', sa.JSON(), nullable=True),
    sa.Column('required', sa.INTEGER(), nullable=True),
    sa.Column('last_used', sa.String(length=32), nullable=True),
    sa.Column('ml_used_per_sample', sa.FLOAT(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.ForeignKeyConstraint(['reagentrole_id'], ['_reagentrole.id'], ),
    sa.PrimaryKeyConstraint('reagentrole_id', 'proceduretype_id')
    )
    op.create_table('_proceduretypetiproleassociation',
    sa.Column('tiprole_id', sa.INTEGER(), nullable=False),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=False),
    sa.Column('uses', sa.JSON(), nullable=True),
    sa.Column('static', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.ForeignKeyConstraint(['tiprole_id'], ['_tiprole.id'], ),
    sa.PrimaryKeyConstraint('tiprole_id', 'proceduretype_id')
    )
    op.create_table('_process_tiprole',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('tiprole_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], ),
    sa.ForeignKeyConstraint(['tiprole_id'], ['_tiprole.id'], )
    )
    op.create_table('_reagent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reagentrole_id', sa.INTEGER(), nullable=True),
    sa.Column('eol_ext', sa.Interval(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cost_per_ml', sa.FLOAT(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['reagentrole_id'], ['_reagentrole.id'], name='fk_REG_reagent_role_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_sample',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('sampletype_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sampletype_id'], ['_sampletype.id'], name='fk_SAMP_sampletype_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_table('_submissiontype_proceduretype',
    sa.Column('submissiontype_id', sa.INTEGER(), nullable=True),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.ForeignKeyConstraint(['submissiontype_id'], ['_submissiontype.id'], )
    )
    op.create_table('_tips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tiprole_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('lot', sa.String(length=64), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tiprole_id'], ['_tiprole.id'], name='fk_tip_role_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_clientsubmissionsampleassociation',
    sa.Column('sample_id', sa.INTEGER(), nullable=False),
    sa.Column('clientsubmission_id', sa.INTEGER(), nullable=False),
    sa.Column('submission_rank', sa.INTEGER(), nullable=False),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clientsubmission_id'], ['_clientsubmission.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['_sample.id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'clientsubmission_id', 'submission_rank')
    )
    op.create_table('_equipment_tips',
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('tips_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], )
    )
    op.create_table('_reagentlot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lot', sa.String(length=64), nullable=True),
    sa.Column('expiry', sa.TIMESTAMP(), nullable=True),
    sa.Column('reagent_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['reagent_id'], ['_reagent.id'], name='fk_REGLOT_reagent_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_reagentrole_reagent',
    sa.Column('reagent_id', sa.INTEGER(), nullable=True),
    sa.Column('reagentrole_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['reagent_id'], ['_reagent.id'], ),
    sa.ForeignKeyConstraint(['reagentrole_id'], ['_reagentrole.id'], )
    )
    op.create_table('_run',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rsl_plate_number', sa.String(length=32), nullable=False),
    sa.Column('clientsubmission_id', sa.INTEGER(), nullable=True),
    sa.Column('_started_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('run_cost', sa.FLOAT(precision=2), nullable=True),
    sa.Column('signed_by', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.JSON(), nullable=True),
    sa.Column('custom', sa.JSON(), nullable=True),
    sa.Column('_completed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clientsubmission_id'], ['_clientsubmission.id'], name='fk_BS_clientsub_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rsl_plate_number')
    )
    op.create_table('_tiprole_tips',
    sa.Column('tiprole_id', sa.INTEGER(), nullable=True),
    sa.Column('tips_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tiprole_id'], ['_tiprole.id'], ),
    sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], )
    )
    op.create_table('_procedure',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('repeat', sa.INTEGER(), nullable=False),
    sa.Column('repeat_of', sa.String(), nullable=True),
    sa.Column('started_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('technician', sa.String(length=64), nullable=True),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=True),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], name='fk_PRO_proceduretype_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['_run.id'], name='fk_PRO_basicrun_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_runsampleassociation',
    sa.Column('sample_id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['_run.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['_sample.id'], ),
    sa.PrimaryKeyConstraint('sample_id', 'run_id')
    )
    op.create_table('_control',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('controltype_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sample_id', sa.String(), nullable=True),
    sa.Column('submitted_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('procedure_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['controltype_name'], ['_controltype.name'], name='fk_BC_subtype_name', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['_sample.id'], name='fk_Cont_sample_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('_procedureequipmentassociation',
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.Column('equipmentrole', sa.String(length=64), nullable=False),
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('tips_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], name='SEA_Process_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], name='SEA_Process_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('equipment_id', 'procedure_id', 'equipmentrole')
    )
    op.create_table('_procedurereagentlotassociation',
    sa.Column('reagentlot_id', sa.INTEGER(), nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.Column('reagentrole', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.String(length=1024), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], ),
    sa.ForeignKeyConstraint(['reagentlot_id'], ['_reagentlot.id'], ),
    sa.PrimaryKeyConstraint('reagentlot_id', 'procedure_id')
    )
    op.create_table('_proceduresampleassociation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.Column('sample_id', sa.INTEGER(), nullable=False),
    sa.Column('row', sa.INTEGER(), nullable=True),
    sa.Column('column', sa.INTEGER(), nullable=True),
    sa.Column('procedure_rank', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['_sample.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'sample_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('_proceduretipsassociation',
    sa.Column('tips_id', sa.INTEGER(), nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.Column('tiprole', sa.String(length=32), nullable=False),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], ),
    sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], ),
    sa.PrimaryKeyConstraint('tips_id', 'procedure_id', 'tiprole')
    )
    op.create_table('_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('result_type', sa.String(length=32), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('date_analyzed', sa.TIMESTAMP(), nullable=True),
    sa.Column('procedure_id', sa.INTEGER(), nullable=True),
    sa.Column('assoc_id', sa.INTEGER(), nullable=True),
    sa.Column('_img', sa.String(length=128), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assoc_id'], ['_proceduresampleassociation.id'], name='fk_RES_ASSOC_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], name='fk_RES_procedure_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_results')
    op.drop_table('_proceduretipsassociation')
    op.drop_table('_proceduresampleassociation')
    op.drop_table('_procedurereagentlotassociation')
    op.drop_table('_procedureequipmentassociation')
    op.drop_table('_control')
    op.drop_table('_runsampleassociation')
    op.drop_table('_procedure')
    op.drop_table('_tiprole_tips')
    op.drop_table('_run')
    op.drop_table('_reagentrole_reagent')
    op.drop_table('_reagentlot')
    op.drop_table('_equipment_tips')
    op.drop_table('_clientsubmissionsampleassociation')
    op.drop_table('_tips')
    op.drop_table('_submissiontype_proceduretype')
    op.drop_table('_sample')
    op.drop_table('_reagent')
    op.drop_table('_process_tiprole')
    op.drop_table('_proceduretypetiproleassociation')
    op.drop_table('_proceduretypereagentroleassociation')
    op.drop_table('_proceduretypeequipmentroleassociation')
    op.drop_table('_proceduretype_process')
    op.drop_table('_equipmentrole_process')
    op.drop_table('_equipmentrole_equipment')
    op.drop_table('_equipment_process')
    op.drop_table('_discount')
    op.drop_table('_clientsubmission')
    op.drop_table('_clientlab_contact')
    op.drop_table('_tiprole')
    op.drop_table('_submissiontype')
    op.drop_table('_sampletype')
    op.drop_table('_reagentrole')
    op.drop_table('_process')
    op.drop_table('_proceduretype')
    op.drop_table('_equipmentrole')
    op.drop_table('_equipment')
    op.drop_table('_controltype')
    op.drop_table('_contact')
    op.drop_table('_configitem')
    op.drop_table('_clientlab')
    # ### end Alembic commands ###
