"""Add active lots to processversion, tipslot, reagentlot

Revision ID: 53913d11bc10
Revises: b8cc2c3abf22
Create Date: 2025-08-15 12:59:50.994699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '53913d11bc10'
down_revision = 'b8cc2c3abf22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_processversion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('_reagentlot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('_tipslot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_tipslot', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('_reagentlot', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('_processversion', schema=None) as batch_op:
        batch_op.drop_column('active')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
