"""Added saved settings to ResultsType

Revision ID: 5491f5ffb268
Revises: 54e03feafdf2
Create Date: 2026-04-24 07:41:52.785362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5491f5ffb268'
down_revision = '54e03feafdf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_resultstype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_saved_settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_resultstype', schema=None) as batch_op:
        batch_op.drop_column('_saved_settings')

    
    # ### end Alembic commands ###
