"""Yet Further Streamlining equipment

Revision ID: 5d63c63c564d
Revises: 318ec502824a
Create Date: 2025-08-14 12:31:30.195084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5d63c63c564d'
down_revision = '318ec502824a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_equipmentrole_equipment',
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], )
    )
    # op.drop_table('_auditlog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.drop_table('_equipmentrole_equipment')
    # ### end Alembic commands ###
