"""Removal of repeat bool from procedure

Revision ID: 61c09254779f
Revises: f3fe82bd28ea
Create Date: 2025-09-04 12:14:02.193441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '61c09254779f'
down_revision = 'f3fe82bd28ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.drop_column('repeat')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat', sa.INTEGER(), nullable=False))

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
