"""_comments everywhere!

Revision ID: 61fe730b724c
Revises: 5491f5ffb268
Create Date: 2026-05-15 14:37:46.310808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '61fe730b724c'
down_revision = '5491f5ffb268'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_clientsubmission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_comment', sa.JSON(), nullable=True))
        batch_op.drop_column('comments')

    with op.batch_alter_table('_clientsubmissionsampleassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_comment', sa.JSON(), nullable=True))

    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_comment', sa.JSON(), nullable=True))

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id', 'procedure_id', 'equipmentrole_id'], ['equipment_id', 'procedure_id', 'equipmentrole_id'])

    with op.batch_alter_table('_proceduresampleassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_comment', sa.JSON(), nullable=True))

    with op.batch_alter_table('_runsampleassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_comment', sa.JSON(), nullable=True))

    with op.batch_alter_table('_sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_comment', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_sample', schema=None) as batch_op:
        batch_op.drop_column('_comment')

    with op.batch_alter_table('_runsampleassociation', schema=None) as batch_op:
        batch_op.drop_column('_comment')

    with op.batch_alter_table('_proceduresampleassociation', schema=None) as batch_op:
        batch_op.drop_column('_comment')

    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.drop_column('_comment')

    with op.batch_alter_table('_clientsubmissionsampleassociation', schema=None) as batch_op:
        batch_op.drop_column('_comment')

    with op.batch_alter_table('_clientsubmission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sqlite.JSON(), nullable=True))
        batch_op.drop_column('_comment')

    # ### end Alembic commands ###
