"""change comment fields to _comment

Revision ID: 6327e46408ef
Revises: cac347f12efd
Create Date: 2026-01-09 08:15:04.525233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6327e46408ef'
down_revision = 'cac347f12efd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_comment', sa.String(length=1024), nullable=True))
        batch_op.drop_column('comments')

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.create_foreign_key("proequiptip_assoc", '_procedureequipmentassociation', ['procedure_id', 'equipment_id', 'equipmentrole_id'], ['procedure_id', 'equipment_id', 'equipmentrole_id'])

    with op.batch_alter_table('_procedurereagentlotassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_comment', sa.String(length=1024), nullable=True))
        batch_op.drop_column('comments')

    with op.batch_alter_table('_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_comment', sa.JSON(), nullable=True))
        batch_op.drop_column('comment')
        batch_op.drop_column('custom')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('comment', sqlite.JSON(), nullable=True))
        batch_op.drop_column('_comment')

    with op.batch_alter_table('_procedurereagentlotassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.VARCHAR(length=1024), nullable=True))
        batch_op.drop_column('_comment')

    with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.VARCHAR(length=1024), nullable=True))
        batch_op.drop_column('_comment')

    op.create_table('_auditlog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    sa.Column('changes', sqlite.JSON(), nullable=True),
    sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
