"""added elution well to ww_sample

Revision ID: 64fec6271a50
Revises: a31943b2284c
Create Date: 2023-05-24 14:43:25.477637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '64fec6271a50'
down_revision = 'a31943b2284c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_ww_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elution_well', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_ww_samples', schema=None) as batch_op:
        batch_op.drop_column('elution_well')
    # ### end Alembic commands ###
