"""Adjusting process-submissionequipassoc

Revision ID: 67fa77849024
Revises: e08a69a0f381
Create Date: 2024-01-05 15:06:24.305945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fa77849024'
down_revision = 'e08a69a0f381'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_equipment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_id', sa.INTEGER(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('SEA_Process_id', '_process', ['process_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('process')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_equipment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint('SEA_Process_id', type_='foreignkey')
        batch_op.create_foreign_key(None, '_process', ['process'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('process_id')

    # ### end Alembic commands ###
