"""Add regex to submissiontype

Revision ID: 69718fcae262
Revises: 6327e46408ef
Create Date: 2026-01-14 10:22:00.351614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '69718fcae262'
down_revision = '6327e46408ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id', 'equipment_id', 'equipmentrole_id'], ['procedure_id', 'equipment_id', 'equipmentrole_id'])

    # with op.batch_alter_table('_run', schema=None) as batch_op:
    #     batch_op.drop_column('custom')
    with op.batch_alter_table("_submissiontype", schema=None) as batch_op:
        batch_op.add_column(sa.Column('regex', sa.VARCHAR(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('_submissionttype', schema=None) as batch_op:
        batch_op.drop_column('regex')
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('_run', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('custom', sqlite.JSON(), nullable=True))

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
