"""Change static setter

Revision ID: 71e9ad044fe3
Revises: 0160a72316f1
Create Date: 2025-12-11 15:42:55.974543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '71e9ad044fe3'
down_revision = '0160a72316f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_proceduretypeequipmentroleassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_static', sa.INTEGER(), nullable=True))
        batch_op.drop_column('static')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_proceduretypeequipmentroleassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('static', sa.INTEGER(), nullable=True))
        batch_op.drop_column('_static')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
