"""Adding equipment clustering

Revision ID: 761baf9d7842
Revises: 3e94fecbbe91
Create Date: 2023-12-18 14:31:21.533319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761baf9d7842'
down_revision = '3e94fecbbe91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cluster_name', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.drop_column('cluster_name')

    # ### end Alembic commands ###
