"""added user tracking

Revision ID: 785bb1140878
Revises: 178203610c3b
Create Date: 2023-02-06 09:54:20.371117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785bb1140878'
down_revision = '178203610c3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.drop_column('uploaded_by')

    # ### end Alembic commands ###
