"""upgrade to procedureequipmenttipslot

Revision ID: 79cf002889ce
Revises: 9ee3b7376c0a
Create Date: 2025-12-24 09:09:01.252879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '79cf002889ce'
down_revision = '9ee3b7376c0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_procedureequipmenttipslotassociation',
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('tipslot_id', sa.INTEGER(), nullable=False),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_procedureequipmentassociation.equipment_id'], ),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_procedureequipmentassociation.equipmentrole_id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedureequipmentassociation.procedure_id'], ),
    sa.ForeignKeyConstraint(['tipslot_id'], ['_tipslot.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'equipment_id', 'equipmentrole_id', 'tipslot_id')
    )
    # op.drop_table('_auditlog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_auditlog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    sa.Column('changes', sqlite.JSON(), nullable=True),
    sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_procedureequipmenttipslotassociation')
    # ### end Alembic commands ###
