"""added required to reagenttype

Revision ID: 7aadd731ff63
Revises: 8d32abdafe2b
Create Date: 2023-07-06 07:58:36.545604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aadd731ff63'
down_revision = '8d32abdafe2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_reagent_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required', sa.INTEGER(), nullable=True))

    # with op.batch_alter_table('_submissions', schema=None) as batch_op:
    #     batch_op.alter_column('rsl_plate_num',
    #            existing_type=sa.VARCHAR(length=32),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('_submissions', schema=None) as batch_op:
    #     batch_op.alter_column('rsl_plate_num',
    #            existing_type=sa.VARCHAR(length=32),
    #            nullable=True)

    with op.batch_alter_table('_reagent_types', schema=None) as batch_op:
        batch_op.drop_column('required')

    # ### end Alembic commands ###
