"""add templates to submission types

Revision ID: 7e7b6eeca468
Revises: 
Create Date: 2023-11-23 08:07:51.103392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7b6eeca468'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submission_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_file', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submission_types', schema=None) as batch_op:
        batch_op.drop_column('template_file')

    # ### end Alembic commands ###
