"""constraints added

Revision ID: 81eb1a777da2
Revises: 61fe730b724c
Create Date: 2026-05-19 10:01:10.855411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '81eb1a777da2'
down_revision = '61fe730b724c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp__clientsubmission')
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_clientlab', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_unique_constraint("clab_name_uni", ['name'])

    # with op.batch_alter_table('_clientsubmission', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('_comment', sa.JSON(), nullable=True))
    #     batch_op.drop_column('comments')

    with op.batch_alter_table('_contact', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_equipmentrole', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id', 'procedure_id', 'equipmentrole_id'], ['equipment_id', 'procedure_id', 'equipmentrole_id'])

    with op.batch_alter_table('_proceduretype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_process', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_reagent', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('ref',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.create_unique_constraint("reagent_ref_uni", ['ref'])

    with op.batch_alter_table('_reagentlot', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_reagentrole', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('_resultstype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.create_unique_constraint("resultstype_name_uni", ['name'])

    with op.batch_alter_table('_submissiontype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('_tipslot', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_tipslot', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_submissiontype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('_resultstype', schema=None) as batch_op:
        batch_op.drop_constraint("resultstype_name_uni", type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_reagentrole', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_reagentlot', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_reagent', schema=None) as batch_op:
        batch_op.drop_constraint("reagent_ref_uni", type_='unique')
        batch_op.alter_column('ref',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_process', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_proceduretype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipmentrole_id'], ['equipmentrole_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id'], ['procedure_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id'], ['equipment_id'])

    with op.batch_alter_table('_equipmentrole', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('_contact', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # with op.batch_alter_table('_clientsubmission', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('comments', sqlite.JSON(), nullable=True))
    #     batch_op.drop_column('_comment')

    with op.batch_alter_table('_clientlab', schema=None) as batch_op:
        batch_op.drop_constraint("clab_name_uni", type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('_alembic_tmp__clientsubmission',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('_submitter_plate_id', sa.VARCHAR(length=127), nullable=True),
    # sa.Column('_submitted_date', sa.TIMESTAMP(), nullable=True),
    # sa.Column('clientlab_id', sa.INTEGER(), nullable=True),
    # sa.Column('submission_category', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('full_batch_size', sa.INTEGER(), nullable=True),
    # sa.Column('contact_id', sa.INTEGER(), nullable=True),
    # sa.Column('submissiontype_name', sa.VARCHAR(), nullable=True),
    # sa.Column('cost_centre', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.Column('_comment', sqlite.JSON(), nullable=True),
    # sa.ForeignKeyConstraint(['clientlab_id'], ['_clientlab.id'], ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['contact_id'], ['_contact.id'], ondelete='SET NULL'),
    # sa.ForeignKeyConstraint(['submissiontype_name'], ['_submissiontype.name'], ondelete='SET NULL'),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('_submitter_plate_id')
    # )
    # ### end Alembic commands ###
