"""updated discount table

Revision ID: 83b06f3f4869
Revises: cc9672a505f5
Create Date: 2023-04-27 13:04:35.886294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '83b06f3f4869'
down_revision = 'cc9672a505f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_discounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_discounts', schema=None) as batch_op:
        batch_op.drop_column('name')
    # ### end Alembic commands ###
