"""added pcr info to wastewater samples

Revision ID: 8adc85dd9b92
Revises: 0ee7ffa026b2
Create Date: 2023-03-27 13:46:06.173379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adc85dd9b92'
down_revision = '0ee7ffa026b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_ww_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pcr_results', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_ww_samples', schema=None) as batch_op:
        batch_op.drop_column('pcr_results')
    # ### end Alembic commands ###
