"""moved artic info to ww_samples

Revision ID: 8d32abdafe2b
Revises: aac569c672de
Create Date: 2023-06-05 10:10:37.650733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d32abdafe2b'
down_revision = 'aac569c672de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_ww_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artic_well_number', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_ww_samples', schema=None) as batch_op:
        batch_op.drop_column('artic_well_number')
    # ### end Alembic commands ###
