"""change to _run_cost

Revision ID: 942bbcec0211
Revises: 1f454c085065
Create Date: 2026-01-15 10:41:01.909338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '942bbcec0211'
down_revision = '1f454c085065'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_run_cost', sa.FLOAT(precision=2), nullable=True))
        batch_op.drop_column('run_cost')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_cost', sa.FLOAT(), nullable=True))
        batch_op.drop_column('_run_cost')
    # ### end Alembic commands ###
