"""adjusting reagents/reagenttypes to many-to-many

Revision ID: 9a133efb3ffd
Revises: 3d9a88bd4ecd
Create Date: 2023-09-01 10:28:22.335890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a133efb3ffd'
down_revision = '3d9a88bd4ecd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_reagenttypes_reagents',
    sa.Column('reagent_id', sa.INTEGER(), nullable=True),
    sa.Column('reagenttype_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['reagent_id'], ['_reagents.id'], ),
    sa.ForeignKeyConstraint(['reagenttype_id'], ['_reagent_types.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_reagenttypes_reagents')
    # ### end Alembic commands ###
