"""add cost per tip

Revision ID: 9c739f1404dd
Revises: 9d7d78d6b6b2
Create Date: 2026-02-13 14:49:49.928783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9c739f1404dd'
down_revision = '9d7d78d6b6b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id', 'procedure_id', 'equipmentrole_id'], ['equipment_id', 'procedure_id', 'equipmentrole_id'])

    with op.batch_alter_table('_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_per_tip', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_tips', schema=None) as batch_op:
        batch_op.drop_column('cost_per_tip')

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id'], ['procedure_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipmentrole_id'], ['equipmentrole_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id'], ['equipment_id'])

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
