"""Adding manufacturer & ref to Regent and Equipment

Revision ID: 9d7d78d6b6b2
Revises: 27ca6bb3e1ab
Create Date: 2026-02-05 14:38:41.602988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9d7d78d6b6b2'
down_revision = '27ca6bb3e1ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('ref', sa.String(length=16), nullable=True))

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id', 'equipment_id', 'equipmentrole_id'], ['procedure_id', 'equipment_id', 'equipmentrole_id'])

    with op.batch_alter_table('_reagent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('ref', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_reagent', schema=None) as batch_op:
        batch_op.drop_column('ref')
        batch_op.drop_column('manufacturer')

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.drop_column('ref')
        batch_op.drop_column('manufacturer')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
