"""Add ranks to RunSampleAssoc and ProcedureSampleAssoc

Revision ID: 9ee3b7376c0a
Revises: 77717c5c894d
Create Date: 2025-12-19 12:12:22.518566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9ee3b7376c0a'
down_revision = '77717c5c894d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_proceduresampleassociation', schema=None) as batch_op:
        batch_op.alter_column('procedure_rank',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('_runsampleassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_rank', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_runsampleassociation', schema=None) as batch_op:
        batch_op.drop_column('run_rank')

    with op.batch_alter_table('_proceduresampleassociation', schema=None) as batch_op:
        batch_op.alter_column('procedure_rank',
               existing_type=sa.INTEGER(),
               nullable=True)

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
