"""Added serial number to equipment

Revision ID: 9efe1be75f12
Revises: a9ee10dca9aa
Create Date: 2026-04-22 10:15:54.236074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9efe1be75f12'
down_revision = 'a9ee10dca9aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=16), nullable=True))

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id', 'procedure_id', 'equipmentrole_id'], ['equipment_id', 'procedure_id', 'equipmentrole_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipmentrole_id'], ['equipmentrole_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id'], ['procedure_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id'], ['equipment_id'])

    with op.batch_alter_table('_equipment', schema=None) as batch_op:
        batch_op.drop_column('serial_number')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
