"""splitting off sample info in SubmissionType

Revision ID: a04c25fd9138
Revises: 6d2a357860ef
Create Date: 2024-05-01 09:11:44.957532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04c25fd9138'
down_revision = '6d2a357860ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('_submissionsampleassociation', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('_submissiontype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_map', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissiontype', schema=None) as batch_op:
        batch_op.drop_column('sample_map')

    # with op.batch_alter_table('_submissionsampleassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
