"""added commenting

Revision ID: a31943b2284c
Revises: 83b06f3f4869
Create Date: 2023-05-10 11:34:30.339915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31943b2284c'
down_revision = '83b06f3f4869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.JSON(), nullable=True))
        

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
