"""change last_used to relationship.

Revision ID: a9ee10dca9aa
Revises: f5f6bb159143
Create Date: 2026-04-15 08:43:17.040641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a9ee10dca9aa'
down_revision = 'f5f6bb159143'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.drop_column('_name')

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id', 'procedure_id', 'equipmentrole_id'], ['equipment_id', 'procedure_id', 'equipmentrole_id'])

    with op.batch_alter_table('_proceduretypereagentroleassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used_lot', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key("lastusedlot", '_reagentlot', ['last_used_lot'], ['lot'])
        batch_op.drop_column('last_used')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_proceduretypereagentroleassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_used_lot')

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id'], ['equipment_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipmentrole_id'], ['equipmentrole_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id'], ['procedure_id'])

    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_name', sa.VARCHAR(), nullable=True))

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
