"""Refining EquipmentRole-> Equipment-> Process relationship

Revision ID: b8cc2c3abf22
Revises: 5d63c63c564d
Create Date: 2025-08-15 09:00:18.239350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b8cc2c3abf22'
down_revision = '5d63c63c564d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_equipmentroleequipmentassociation',
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], ),
    sa.PrimaryKeyConstraint('equipmentrole_id', 'equipment_id')
    )
    op.drop_table('_equipmentrole_equipment')
    # op.drop_table('_auditlog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.create_table('_equipmentrole_equipment',
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], )
    )
    op.drop_table('_equipmentroleequipmentassociation')
    # ### end Alembic commands ###
