"""adding submission category

Revision ID: b95478ffb4a3
Revises: 9a133efb3ffd
Create Date: 2023-10-03 14:00:09.663055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95478ffb4a3'
down_revision = '9a133efb3ffd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_category', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissions', schema=None) as batch_op:
        batch_op.drop_column('submission_category')

    # ### end Alembic commands ###
