"""Streamlining equipment

Revision ID: b99debc3ed31
Revises: c97df35f22cd
Create Date: 2025-08-14 10:30:57.000401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b99debc3ed31'
down_revision = 'c97df35f22cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('_process_tips',
    # sa.Column('process_id', sa.INTEGER(), nullable=True),
    # sa.Column('tips_id', sa.INTEGER(), nullable=True),
    # sa.ForeignKeyConstraint(['process_id'], ['_process.id'], ),
    # sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], )
    # )
    # op.create_table('_tipslot',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('tips_id', sa.INTEGER(), nullable=True),
    # sa.Column('lot', sa.String(length=64), nullable=True),
    # sa.Column('expiry', sa.TIMESTAMP(), nullable=True),
    # sa.Column('_misc_info', sa.JSON(), nullable=True),
    # sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], name='fk_tips_id', ondelete='SET NULL'),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('lot')
    # )
    # op.create_table('_proceduretypeequipmentroleassociation_equipment',
    # sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    # sa.Column('proceduretypeequipmentroleassociation_proceduretypeid', sa.INTEGER(), nullable=True),
    # sa.Column('proceduretypeequipmentroleassociation_equipmentroleid', sa.INTEGER(), nullable=True),
    # sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    # sa.ForeignKeyConstraint(['proceduretypeequipmentroleassociation_equipmentroleid'], ['_proceduretypeequipmentroleassociation.equipmentrole_id'], ),
    # sa.ForeignKeyConstraint(['proceduretypeequipmentroleassociation_proceduretypeid'], ['_proceduretypeequipmentroleassociation.proceduretype_id'], )
    # )
    # op.drop_table('_proceduretypetiproleassociation')
    # op.drop_table('_proceduretipsassociation')
    # op.drop_table('_proceduretype_process')
    # op.drop_table('_equipmentrole_equipment')
    # op.drop_table('_tiprole')
    # op.drop_table('_equipment_tips')
    # op.drop_table('_equipmentrole_process')
    # op.drop_table('_process_tiprole')
    # op.drop_table('_tiprole_tips')
    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipslot_id', sa.INTEGER(), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('SEA_Tipslot_id', '_tipslot', ['tipslot_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('tips_id')

    with op.batch_alter_table('_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        # batch_op.drop_constraint('fk_tip_role_id', type_='foreignkey')
        # batch_op.drop_column('tiprole_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiprole_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_tip_role_id', '_tiprole', ['tiprole_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('name')

    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tips_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('SEA_Tipslot_id', type_='foreignkey')
        batch_op.create_foreign_key(None, '_tips', ['tips_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('tipslot_id')

    op.create_table('_tiprole_tips',
    sa.Column('tiprole_id', sa.INTEGER(), nullable=True),
    sa.Column('tips_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tiprole_id'], ['_tiprole.id'], ),
    sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], )
    )
    op.create_table('_process_tiprole',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('tiprole_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], ),
    sa.ForeignKeyConstraint(['tiprole_id'], ['_tiprole.id'], )
    )
    op.create_table('_equipmentrole_process',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], )
    )
    op.create_table('_equipment_tips',
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('tips_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], )
    )
    op.create_table('_tiprole',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_equipmentrole_equipment',
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipmentrole.id'], )
    )
    op.create_table('_proceduretype_process',
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], )
    )
    op.create_table('_proceduretipsassociation',
    sa.Column('tips_id', sa.INTEGER(), nullable=False),
    sa.Column('procedure_id', sa.INTEGER(), nullable=False),
    sa.Column('tiprole', sa.VARCHAR(length=32), nullable=False),
    sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['_procedure.id'], ),
    sa.ForeignKeyConstraint(['tips_id'], ['_tips.id'], ),
    sa.PrimaryKeyConstraint('tips_id', 'procedure_id', 'tiprole')
    )
    op.create_table('_proceduretypetiproleassociation',
    sa.Column('tiprole_id', sa.INTEGER(), nullable=False),
    sa.Column('proceduretype_id', sa.INTEGER(), nullable=False),
    sa.Column('uses', sqlite.JSON(), nullable=True),
    sa.Column('static', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['proceduretype_id'], ['_proceduretype.id'], ),
    sa.ForeignKeyConstraint(['tiprole_id'], ['_tiprole.id'], ),
    sa.PrimaryKeyConstraint('tiprole_id', 'proceduretype_id')
    )
    op.drop_table('_equipmentroleproceduretypeassociation_equipment')
    op.drop_table('_tipslot')
    op.drop_table('_process_tips')
    # ### end Alembic commands ###
