"""Adding equipment roles

Revision ID: bc7a74476609
Revises: 761baf9d7842
Create Date: 2023-12-21 10:44:23.520392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'bc7a74476609'
down_revision = '761baf9d7842'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_equipment_roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_equipmentroles_equipment',
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('equipmentroles_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['equipmentroles_id'], ['_equipment_roles.id'], )
    )
    op.create_table('_submissiontype_equipmentrole',
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=False),
    sa.Column('submissiontype_id', sa.INTEGER(), nullable=False),
    sa.Column('uses', sa.JSON(), nullable=True),
    sa.Column('static', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipmentrole_id'], ['_equipment_roles.id'], ),
    sa.ForeignKeyConstraint(['submissiontype_id'], ['_submission_types.id'], ),
    sa.PrimaryKeyConstraint('equipmentrole_id', 'submissiontype_id')
    )
    op.drop_table('_submissiontype_equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_submissiontype_equipment',
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('submissiontype_id', sa.INTEGER(), nullable=False),
    sa.Column('uses', sqlite.JSON(), nullable=True),
    sa.Column('static', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['_equipment.id'], ),
    sa.ForeignKeyConstraint(['submissiontype_id'], ['_submission_types.id'], ),
    sa.PrimaryKeyConstraint('equipment_id', 'submissiontype_id')
    )
    op.drop_table('_submissiontype_equipmentrole')
    op.drop_table('_equipmentroles_equipment')
    op.drop_table('_equipment_roles')
    # ### end Alembic commands ###
