"""Unique reagent lots

Revision ID: c97df35f22cd
Revises: 2578b0c4adf8
Create Date: 2025-08-13 13:37:13.701168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c97df35f22cd'
down_revision = '2578b0c4adf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_reagentlot', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_reagentlot", ['lot'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_reagentlot', schema=None) as batch_op:
        batch_op.drop_constraint("unique_reagentlot", type_='unique')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
