"""change process->ereassoc to many to many

Revision ID: cac347f12efd
Revises: 79cf002889ce
Create Date: 2025-12-29 14:27:15.890780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cac347f12efd'
down_revision = '79cf002889ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_equipmentrolequipmentassociation_process',
    sa.Column('equipmentrole_id', sa.INTEGER(), nullable=True),
    sa.Column('equipment_id', sa.INTEGER(), nullable=True),
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('pk_constraint', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['equipmentrole_id', 'equipment_id'], ['_equipmentroleequipmentassociation.equipmentrole_id', '_equipmentroleequipmentassociation.equipment_id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], ),
    sa.PrimaryKeyConstraint('pk_constraint')
    )
    # op.drop_table('_auditlog')
    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id', 'equipment_id', 'equipmentrole_id'], ['procedure_id', 'equipment_id', 'equipmentrole_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.drop_table('_equipmentrolequipmentassociation_process')
    # ### end Alembic commands ###
