"""Adding static option to equipSTASsoc

Revision ID: cd11db3794ed
Revises: 36a47d8837ca
Create Date: 2023-12-12 14:47:20.924443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd11db3794ed'
down_revision = '36a47d8837ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissiontype_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('static', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_submissiontype_equipment', schema=None) as batch_op:
        batch_op.drop_column('static')

    # ### end Alembic commands ###
