"""Update to ProcedureEquipmentAssociation

Revision ID: db76a5452c47
Revises: 61c09254779f
Create Date: 2025-10-07 14:30:23.643172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'db76a5452c47'
down_revision = '61c09254779f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipmentrole_id', sa.INTEGER(), nullable=False, default=1))
        batch_op.create_foreign_key("fk_equiprole_proeqassoc", '_equipmentrole', ['equipmentrole_id'], ['id'])
        batch_op.drop_column('equipmentrole')

    # with op.batch_alter_table('_proceduretype', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['name'])
    #
    # with op.batch_alter_table('_reagent', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['name'])
    #
    # with op.batch_alter_table('_reagentrole', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_reagentrole', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('_reagent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('_proceduretype', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('_procedureequipmentassociation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipmentrole', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipmentrole_id')


    # ### end Alembic commands ###
