"""split mutable costs into 96 and 24

Revision ID: dc780c868efd
Revises: 83b06f3f4869
Create Date: 2023-05-01 14:05:47.762441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'dc780c868efd'
down_revision = '83b06f3f4869'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp__kits')
    with op.batch_alter_table('_kits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mutable_cost_96', sa.FLOAT(precision=2), nullable=True))
        batch_op.add_column(sa.Column('mutable_cost_24', sa.FLOAT(precision=2), nullable=True))
        batch_op.drop_column('mutable_cost')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('_kits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mutable_cost', sa.FLOAT(), nullable=True))
        batch_op.drop_column('mutable_cost_24')
        batch_op.drop_column('mutable_cost_96')

    op.create_table('_alembic_tmp__kits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('used_for', sqlite.JSON(), nullable=True),
    sa.Column('cost_per_run', sa.FLOAT(), nullable=True),
    sa.Column('reagent_types_id', sa.INTEGER(), nullable=True),
    sa.Column('constant_cost', sa.FLOAT(), nullable=True),
    sa.Column('mutable_cost_96', sa.FLOAT(), nullable=True),
    sa.Column('mutable_cost_24', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['reagent_types_id'], ['_reagent_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
