"""Adding info, samples to resultstype

Revision ID: de7fcdcbcc4b
Revises: 942bbcec0211
Create Date: 2026-01-15 14:27:20.288141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'de7fcdcbcc4b'
down_revision = '942bbcec0211'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_resultstype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('_samples', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_resultstype', schema=None) as batch_op:
        batch_op.drop_column('_samples')
        batch_op.drop_column('_info')

    
    # ### end Alembic commands ###
