"""Attempt at self referential procedure (for repeats)

Revision ID: f3fe82bd28ea
Revises: 53913d11bc10
Create Date: 2025-09-03 11:28:28.297696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f3fe82bd28ea'
down_revision = '53913d11bc10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_of_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_repeat_id', '_procedure', ['repeat_of_id'], ['id'])
        batch_op.drop_column('repeat_of')

    # with op.batch_alter_table('_tips', schema=None) as batch_op:
    #     batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))

    with op.batch_alter_table('_procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_of', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_repeat_id', type_='foreignkey')
        batch_op.drop_column('repeat_of_id')

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
