"""remove sampe_count from clientsubmission

Revision ID: f5f6bb159143
Revises: 9c739f1404dd
Create Date: 2026-02-16 14:54:15.059946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f5f6bb159143'
down_revision = '9c739f1404dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_auditlog')
    with op.batch_alter_table('_clientsubmission', schema=None) as batch_op:
        batch_op.drop_column('sample_count')

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id', 'procedure_id', 'equipmentrole_id'], ['equipment_id', 'procedure_id', 'equipmentrole_id'])

    # with op.batch_alter_table('_tips', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('_cost_per_tip', sa.FLOAT(precision=2), nullable=True))
    #     batch_op.drop_column('cost_per_tip')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('_tips', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('cost_per_tip', sa.FLOAT(), nullable=True))
    #     batch_op.drop_column('_cost_per_tip')

    # with op.batch_alter_table('_procedureequipmenttipslotassociation', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipment_id'], ['equipment_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['equipmentrole_id'], ['equipmentrole_id'])
    #     batch_op.create_foreign_key(None, '_procedureequipmentassociation', ['procedure_id'], ['procedure_id'])

    with op.batch_alter_table('_clientsubmission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_count', sa.INTEGER(), nullable=True))

    # op.create_table('_auditlog',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('time', sa.TIMESTAMP(), nullable=True),
    # sa.Column('object', sa.VARCHAR(length=64), nullable=True),
    # sa.Column('changes', sqlite.JSON(), nullable=True),
    # sa.Column('_misc_info', sqlite.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
