"""Adding ProcessVersion

Revision ID: fb71f3fd1bda
Revises: 522441c4c3d6
Create Date: 2025-08-11 10:11:14.330053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fb71f3fd1bda'
down_revision = '522441c4c3d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_processversion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('date_verified', sa.TIMESTAMP(), nullable=True),
    sa.Column('project', sa.String(length=128), nullable=True),
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('_misc_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['_process.id'], name='fk_version_process_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_processversion')
    # ### end Alembic commands ###
