logging_enabled: false
directories:
  main: null
  backup: null
database:
  name: null
  path: null
  schema: null
  user: null
  password: null
irida_next:
  email: null
  token: null
  endpoint: null